swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Title"
  description: "API Description"
host: "localhost:3000"
basePath: "/"
schemes:
  - "http"
paths:
  /store/add:
    post:
      tags:
        - Store
      summary: 특정 지역에 가게 추가
      parameters:
        - name: storeInfo
          in: body
          required: true
          schema:
            properties:
              name:
                type: string
                description: 가게 이름
                example: "식당이름"
              address:
                type: string
                description: 가게 주소
                example: "성남시 수정구 복정동"
              area:
                type: string
                description: 가게가 위치한 지역
                example: "복정동"
      responses:
        '200':
          description: 가게 추가 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "가게가 성공적으로 추가되었습니다."
              data:
                type: object
                properties:
                  storeId:
                    type: integer
                    example: 789
                  name:
                    type: string
                    example: "식당이름"
                  address:
                    type: string
                    example: "성남시 수정구 복정동"
                  area:
                    type: string
                    example: "복정"
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다."
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."

  /store/review:
    post:
      tags:
        - Store
      summary: 가게 리뷰 작성
      parameters:
        - name: review
          in: body
          required: true
          schema:
            properties:
              storeId:
                type: integer
                description: 가게 ID
                example: 123
              userId:
                type: integer
                description: 사용자 ID
                example: 456
              rating:
                type: integer
                description: 평점 (1부터 5까지)
                example: 4
              comment:
                type: string
                description: 리뷰 내용
                example: "맛있어요"
      responses:
        '200':
          description: 리뷰 작성 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "리뷰가 성공적으로 작성되었습니다."
              data:
                type: object
                properties:
                  reviewId:
                    type: integer
                    example: 789
                  storeId:
                    type: integer
                    example: 123
                  userId:
                    type: integer
                    example: 456
                  rating:
                    type: integer
                    example: 4
                  comment:
                    type: string
                    example: "맛있어요"
        '400':
          description: 잘못된 요청 또는 가게가 존재하지 않음
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다."
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."
  
  /store/mission/add:
    post:
      tags:
        - Store
      summary: 가게에 미션 추가
      parameters:
        - name: missionInfo
          in: body
          required: true
          schema:
            properties:
              storeId:
                type: integer
                description: 가게 ID
                example: 123
              missionName:
                type: string
                description: 미션 이름
                example: "마라탕 15000원 이상 주문하기"
              condition:
                type: object
                description: 미션 달성 조건
                properties:
                  orderAmount:
                    type: integer
                    description: 주문 금액 조건
                    example: 15000
      responses:
        '200':
          description: 미션 추가 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "미션이 성공적으로 추가되었습니다."
              data:
                type: object
                properties:
                  missionId:
                    type: integer
                    example: 789
                  storeId:
                    type: integer
                    example: 123
                  missionName:
                    type: string
                    example: "마라탕 15000원 이상 주문하기"
                  condition:
                    type: object
                    properties:
                      orderAmount:
                        type: integer
                        example: 15000
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "잘못된 요청입니다."
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."    

  /store/mission/challenge:
    post:
      tags:
        - Store
      summary: 가게의 미션 도전하기
      parameters:
        - name: challengeInfo
          in: body
          required: true
          schema:
            properties:
              userId:
                type: integer
                description: 유저 ID
                example: 456
              storeId:
                type: integer
                description: 가게 ID
                example: 123
              missionId:
                type: integer
                description: 미션 ID
                example: 789
      responses:
        '200':
          description: 미션 도전 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "미션이 성공적으로 도전되었습니다."
              data:
                type: object
                properties:
                  missionStatus:
                    type: string
                    example: "ONGOING"
        '400':
          description: 잘못된 요청 또는 이미 도전 중인 미션
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: "이미 도전 중인 미션입니다."
        '404':
          description: 미션 또는 가게가 존재하지 않음
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON002
              message:
                type: string
                example: "미션 또는 가게가 존재하지 않습니다."
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: "서버 에러, 관리자에게 문의 바랍니다."